# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["develop"]

jobs:
  call-workflow:
    uses: gurukulams/design-system/.github/workflows/material-deploy.yml@main
    with:
      # Pass any required inputs here
      GithubOrg: "tnebooks" 
    secrets: inherit # If the sub-workflow needs access to secrets