jobs:
  call-workflow:
    uses: gurukulams/design-system/.github/workflows/material-deploy.yml@main
    with:
      # Pass any required inputs here
      GithubOrg: "tnebooks" 
    secrets: inherit # If the sub-workflow needs access to secrets